menu:
  Home: /
  Archives: /archives
  About: /about
  
social:
# key weibo/twitter/google/github/stackoverflow/rss
# value url
# e.g github: https://github.com/mcwanghui
  github: https://github.com/mcwanghui
  weibo: http://weibo.com/mcwanghui
  rss: /atom.xml

favicon: /favicon.ico

widgets:
- search
- category
- recent_posts
#- intro
#- weibo
- tag
- tagcloud
- links

excerpt_link: 阅读全文

fancybox: true

#google_analytics: UA-41207871-1
baidu__tongji: true 

