menu:
  Home: /
  Archives: /archives
  About: /about
  
rss: /atom.xml

favicon: /favicon.png

widgets:
- search
- category
- recent_posts
#- intro
#- weibo
- tag
- tagcloud
- links

excerpt_link: 阅读全文

fancybox: true

#google_analytics: UA-41207871-1
#baidu__analytics: 

